# Site settings
author: Erik
title: Stepping forward 
header-img: img/home-bg.png
email: chefkasperson@gmail.com
copyright_name: Erik
description: > # this means to ignore newlines until "baseurl:"
  Journey through bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chefkasperson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
